-- AlterTable
ALTER TABLE "QuoteItem" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "negotiatedPrice" DOUBLE PRECISION,
ADD COLUMN     "remarks" TEXT;
